format = """
[░▒▓](#7aa2f7)\
[🐧](bg:#7aa2f7 fg:#1a1b26)\
[](bg:#9d7cd8 fg:#7aa2f7)\
$directory\
[](fg:#9d7cd8 bg:#3b4261)\
$git_branch\
$git_status\
[](fg:#3b4261 bg:#2a2e3f)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2a2e3f bg:#1a1b26)\
$time\
[ ](fg:#1a1b26)\
\n$character"""

[directory]
style = "fg:#c0caf5 bg:#9d7cd8"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3b4261"
format = '[[ $symbol $branch ](fg:#7aa2f7 bg:#3b4261)]($style)'

[git_status]
style = "bg:#3b4261"
format = '[[($all_status$ahead_behind )](fg:#7aa2f7 bg:#3b4261)]($style)'

[nodejs]
symbol = ""
style = "bg:#2a2e3f"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#2a2e3f)]($style)'

[rust]
symbol = ""
style = "bg:#2a2e3f"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#2a2e3f)]($style)'

[golang]
symbol = ""
style = "bg:#2a2e3f"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#2a2e3f)]($style)'

[php]
symbol = ""
style = "bg:#2a2e3f"
format = '[[ $symbol ($version) ](fg:#7aa2f7 bg:#2a2e3f)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#1a1b26"
format = '[[  $time ](fg:#9ece6a bg:#1a1b26)]($style)'

