site_name: Wanchufley's Documentation 
site_url: https://xrxapp.org
site_description: Personal documentation and configuration files
site_author: Wanchufley

theme:
  name: material
  custom_dir: ./docs/overrides/
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.follow
  icon:
    logo: material/alpha-w
  favicon: assets/img/favicon.ico

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Wanchufley

extra_css:
  - stylesheets/cards.css
  - stylesheets/extra.css

nav:
  - 🏠 Home: index.md
  - 👤 About: about.md
  - 🏷️ Tags: tags.md 
  - 📁 Files: file-explorer.md
  - 📝 Posts:
      - Figurine Installation: posts/post-01-figurine-install.md
      - UFW Role: posts/post-02-ufw-role.md
      - Dotfile Management: posts/post-03-dotfile-mgmnt.md
      - NPM Installation: posts/post-04-npm-installation.md
  - 📚 Resources:
      - Docker:
          - Restic Restore: resources/docker/restic/restic-restore.md
      - Dotfiles:
          - README: resources/dotfiles/README.md
#  - 🤝 Sponsor: sponsor.md

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags:
      enabled: true
      tags_file: tags.md
      tags_extra_files:
        tags.md: "Tags"

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

